### ISSUE TITLE
How do I start IntellijIDEA in your acntech/ubuntu64-dev box?

### ISSUE THREAD

**Issue by Muzietto** [acntech/vagrant-ubuntu#6]
I have downloaded your `ubuntu64` box from Atlas.

All the Vagrant operations work without problem and I can start the VM with

```
  vagrant ssh -- -X
```

Now I am inside the VM but I cannot find where `idea.sh` the start script of IDEA is. Can you please tell me where IntellijIDEA is installed?

I have tried a few canonical locations, without finding it.

Thank you very much for your attention.

**Comment by onlyteo** [comment]
Hi,

The [acntech/ubuntu64](https://atlas.hashicorp.com/acntech/boxes/ubuntu64) box on Atlas is only a basic Ubuntu image with Puppet installed. The [acntech/ubuntu64-dev](https://atlas.hashicorp.com/acntech/boxes/ubuntu64-dev) is the box created from the [acntech/vagrant-ubuntu](https://github.com/acntech/vagrant-ubuntu) Github repo. It has development tools installed. This box however is not completely bug free.

We have switched to using Xubuntu instead, which is not as heavy on the resources as regular Ubuntu.
For the developer version of Xubuntu use [acntech/xubuntu-developer](https://atlas.hashicorp.com/acntech/boxes/xubuntu-developer)

**Comment by Muzietto** [comment]
Thank you for your fast reply, and apologies for writing the wrong box name. I have corrected the title of the issue. I am indeed talking of the dev box.

I see your boxes as a valuable study aid, because I am learning Vagrant. My question is probably more general than it appears.

**How do I start the GUI of IntellijIDEA on your dev Vagrant box?**

Or even better:

**How do I go about exploring the various configuration files in order to discover the settings of the various apps provisioned originally on the box?**

I will try anyway your xubuntu-developer box :-)  Thank you very much for your attention and patience.

**Comment by onlyteo** [comment]
You should be able to find the IntelliJ icon in the Unity menu from the desktop.
If you rather like to start it from the command line you will find it installed under the /opt directory.

Most of the provisioning of the box is done by Puppet. See the puppet folder of this repo for details.

**Comment by Muzietto** [comment]
Perfect. Thank you.
